settings:
  #username: "Readme-Workflows" # Replace with your username or comment out this line
  commit_msg: "Update README with the recent activity"
  max_lines: 5
  readme_file: "./README.md"
  date:
    text: "Last Updated: {DATE} (GMT)"
